In [1]:
from google.colab import files
uploaded = files.upload()

Saving datasets_3354_5457_Documents.csv to datasets_3354_5457_Documents.csv


#IMPORTING LIBRARIES

In [4]:
import seaborn
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn import metrics

import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [5]:
dataset = pd.read_csv("datasets_3354_5457_Documents.csv")
dataset.head()

SMS_id                                                SMS
0       1   \tGo until jurong point, crazy.. Available on...
1       2                  \tOk lar... Joking wif u oni...\n
2       3   \tFree entry in 2 a wkly comp to win FA Cup f...
3       4   \tU dun say so early hor... U c already then ...
4       5   \tNah I don't think he goes to usf, he lives ...

#HANDLING CATEGORICAL DATA

In [6]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
x = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values 
labelencoder_X = LabelEncoder()
x[:,0] = labelencoder_X.fit_transform(x[:,0])
#x[:,1] = labelencoder_X.fit_transform(x[:,1])
print(x)
#Here we are using LabelEncoder

[[   0]
 [   1]
 [   2]
 ...
 [5571]
 [5572]
 [5573]]


In [7]:
x = dataset[['SMS_id']]
#separate the other attributes from the predicting attribute

In [8]:
y = dataset[['SMS']]
#separte the predicting attribute into Y for model training 

#SPLITTING OF DATASET INTO TRAIN AND TEST SET

In [9]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(x, y, test_size = 0.25, random_state = 0)

#NORMALIZING DATA

In [10]:
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

#ALGORITHM

In [11]:
classifier = svm.SVC(kernel ='linear')

#FITTING OF TRAINING DATA

In [12]:
classifier.fit(X_Train,Y_Train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#PREDICTIONS FOR OUR PROBLEM STATEMENT WITH THE RELATED GRAPHS

In [13]:
Y_Pred = classifier.predict(X_Test)

#SAVING THE MODEL USING PICKLE LIBRARY

In [14]:
import pickle 

# Save the trained model as a pickle string. 
saved_model = pickle.dumps(classifier) 

# Load the pickled model 
model_from_pickle = pickle.loads(saved_model) 

# Use the loaded pickled model to make predictions 
model_from_pickle.predict(X_Test) 


array([" \tSorry, I'll call later\n", " \tSorry, I'll call later\n",
       " \tSorry, I'll call later\n", ..., " \tSorry, I'll call later\n",
       " \tSorry, I'll call later\n", " \tSorry, I'll call later\n"],
      dtype=object)

#ACCURACY

In [15]:
print(metrics.accuracy_score(Y_Test, Y_Pred))

0.007173601147776184


#ACCURACY w.r.t TRAINED DATA

Confusion Matrix

In [17]:
Y_Train = Y_Train[0:116]
Y_Pred =Y_Pred[0:116]
cm = confusion_matrix(Y_Train, Y_Pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Precision, Recall, Support, Fscore

In [18]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(Y_Train, Y_Pred, average='macro')

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(7.496251874062968e-05, 0.008695652173913044, 0.00014864362690449647, None)

#ACCURACY w.r.t TEST DATA

Confusion Matrix

In [19]:
Y_Test = Y_Test[0:116]
results =confusion_matrix(Y_Test, Y_Pred)
print(results)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Precision, Recall, Support, Fscore

In [20]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(Y_Test, Y_Pred, average='macro')

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.0, 0.0, 0.0, None)