In [ ]:
from google.colab import files
uploaded = files.upload()

Saving datasets_3354_5457_Documents.csv to datasets_3354_5457_Documents.csv


#IMPORTING LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
dataset= pd.read_csv('datasets_3354_5457_Documents.csv')
dataset.describe()
dataset.head()

SMS_id                                                SMS
0       1   \tGo until jurong point, crazy.. Available on...
1       2                  \tOk lar... Joking wif u oni...\n
2       3   \tFree entry in 2 a wkly comp to win FA Cup f...
3       4   \tU dun say so early hor... U c already then ...
4       5   \tNah I don't think he goes to usf, he lives ...

#HANDLING CATEGORICAL DATA

In [ ]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
dataset = pd.read_csv('datasets_3354_5457_Documents.csv') 
x = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values 
labelencoder_X = LabelEncoder()
#dataset = dataset.apply(lambda col: labelencoder_X.fit_transform(col), axis=0, result_type='expand')
x[:,0] = labelencoder_X.fit_transform(x[:,0])
#x[:,1] = labelencoder_X.fit_transform(x[:,1])
print(x)
#Here we are using LabelEncoder

[[   0]
 [   1]
 [   2]
 ...
 [5571]
 [5572]
 [5573]]


In [ ]:
x = dataset[['SMS_id']]
#separate the other attributes from the predicting attribute

In [ ]:
y = dataset[['SMS']]
#separte the predicting attribute into Y for model training 

#SPLITTING OF DATASET INTO TRAIN AND TEST SET

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

#NORMALIZING DATA

In [ ]:
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(x_train)

# transform training data
X_train_norm = norm.transform(x_train)

# transform testing data
X_test_norm = norm.transform(x_test)

print(X_train_norm)
print(X_test_norm)

[[0.45271846]
 [0.04539745]
 [0.19989234]
 ...
 [0.29660865]
 [0.46779114]
 [0.49022071]]
[[0.83994258]
 [0.82899695]
 [0.79382738]
 ...
 [0.4401579 ]
 [0.22824332]
 [0.2311143 ]]


#ALGORITHM

In [ ]:
model =LogisticRegression()
#loading the model constructor

#FITTING OF TRAINING DATA

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
print('Intercept is :',model.intercept_)

Intercept is : [-5.14217953e-06 -1.79493364e-06 -1.37784029e-05 ...  1.35440332e-05
  8.30710186e-07 -2.14488504e-06]


In [ ]:
print('Coefficient is :' ,model.coef_)

Coefficient is : [[ 1.30446201e-04]
 [ 1.06082011e-04]
 [ 1.83479637e-04]
 ...
 [-3.96215132e-05]
 [ 8.60758147e-05]
 [ 1.08643810e-04]]


#PREDICTIONS FOR OUR PROBLEM STATEMENT WITH THE RELATED GRAPHS

In [ ]:
predictions = model.predict(x_test)

#SAVING THE MODEL USING PICKLE LIBRARY

In [ ]:
import pickle 

# Save the trained model as a pickle string. 
saved_model = pickle.dumps(model) 

# Load the pickled model 
model_from_pickle = pickle.loads(saved_model) 

# Use the loaded pickled model to make predictions 
model_from_pickle.predict(x_test) 


array([" \tSorry, I'll call later\n", " \tSorry, I'll call later\n",
       " \tSorry, I'll call later\n", ..., " \tSorry, I'll call later\n",
       " \tSorry, I'll call later\n", " \tSorry, I'll call later\n"],
      dtype=object)

#ACCURACY

In [ ]:
print(metrics.accuracy_score(y_test, predictions))

0.008071748878923767


#ACCURACY w.r.t TRAINED DATA

Confusion Matrix

In [ ]:
y_train = y_train[0:74]

In [ ]:
from sklearn.metrics import confusion_matrix

predictions=predictions[0:74]

results =confusion_matrix(y_train, predictions)
print(results)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Precision, Recall, Support, Fscore

In [ ]:
import numpy
from sklearn.metrics import precision_recall_fscore_support


precision_recall_fscore_support(y_train, predictions, average='macro')

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.00018261504747991235, 0.013513513513513514, 0.0003603603603603603, None)

#ACCURACY w.r.t TEST DATA

Confusion Matrix

In [ ]:
y_test=y_test[0:74]

results =confusion_matrix(y_test, predictions)
print(results)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Precision, Recall, Support, Fscore

In [ ]:
import numpy
from sklearn.metrics import precision_recall_fscore_support


precision_recall_fscore_support(y_test, predictions, average='macro')

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.0, 0.0, 0.0, None)